export const GET_RESERVATIONS = 'GET_RESERVATIONS';
export const GET_RESERVATION_SUGGESTED_SEATS = 'GET_RESERVATION_SUGGESTED_SEATS';

export const GET_SEATS_BY_SHOWTIME = 'GET_SEATS_BY_SHOWTIME';
export const SET_ORDER_NON_PAYMENT = 'SET_ORDER_NON_PAYMENT';
export const SET_IS_APPLY_PROMOTION = 'SET_IS_APPLY_PROMOTION';
